// Product copy that is shared between pages. Source of truth: the product brief.
export const DISCLAIMER = "Variable returns. Capital at risk. StockYield does not guarantee yield or principal.";
export const NON_AFFILIATION = "StockYield is an independent interface and is not affiliated with Robinhood, Morpho or Steakhouse.";
export const YIELD_SOURCE = "Your USDG is deposited into the Steakhouse vault, which allocates assets to lending markets on Morpho. Borrowers pay interest. Returns vary with market conditions, allocations and fees.";

export const RISKS: { id: string; title: string; short: string; body: string }[] = [
  { id: "smart-contract", title: "Smart contract", short: "Bugs or exploits in the contracts used.", body: "Your funds are held by the Steakhouse USDG vault, which allocates to Morpho lending markets, and the asset is USDG. A bug or exploit in any of these contracts, or in the adapters between them, could cause partial or total loss. StockYield has not audited them and does not claim that they have been audited." },
  { id: "liquidity", title: "Liquidity", short: "Withdrawals depend on available liquidity.", body: "Withdrawals are served from idle assets and from liquidity in the underlying lending markets. If borrowers are using most of it, a withdrawal can be limited or delayed until liquidity returns. The liquidity figure shown is a snapshot reported by the Morpho API; the amount you can actually withdraw is checked by a simulation before you sign." },
  { id: "oracle", title: "Oracle", short: "Some markets rely on price feeds.", body: "Some underlying lending markets value collateral with oracle price feeds. A wrong, stale or manipulated price can trigger incorrect liquidations or leave loans under-collateralized." },
  { id: "bad-debt", title: "Bad debt", short: "Insufficient liquidations can cause losses.", body: "If collateral loses value faster than liquidations can cover a loan, the unpaid part becomes bad debt and can reduce what lenders in that market, and therefore the vault, can withdraw. As a depositor you are not personally liquidated; your exposure is to losses in the underlying markets." },
  { id: "stablecoin", title: "Stablecoin", short: "USDG can lose its peg.", body: "USDG is intended to stay close to one US dollar but can trade away from it, and it depends on its issuer, its reserves and the rules that apply to them. A depeg or an issuer problem affects the value of your position directly." },
  { id: "variable-apy", title: "Variable APY", short: "The yield can rise, fall or be zero.", body: "The APY moves with borrowing demand, market utilization, allocations, fees and rewards. It can increase, decrease or be zero, and a past or current rate is not a promise of a future one." },
  { id: "vault-management", title: "Vault management", short: "Allocations and settings follow the vault's roles.", body: "Which markets receive your funds, the limits on them and the vault's fees are set through the roles configured in the vault, for example by its curator and owner, within the rules of the contract. These settings can change. StockYield does not manage the vault or its allocations." },
  { id: "network", title: "Network", short: "Network or RPC problems can block access.", body: "Robinhood Chain, its RPC endpoints or the data provider can be slow, unavailable or wrong for a while. That can temporarily prevent you from seeing your position, simulating or sending a transaction. When data is missing StockYield shows “Unavailable” instead of a number." },
];

export const FAQ: { q: string; a: string }[] = [
  { q: "What is StockYield?", a: "An independent, non-custodial web interface for depositing USDG into the Steakhouse USDG vault on Morpho, on Robinhood Chain. It shows live data, prepares and simulates transactions, and shows your position. You sign every transaction yourself." },
  { q: "Where does the yield come from?", a: YIELD_SOURCE },
  { q: "Does StockYield hold my funds?", a: "No. Funds go from your wallet directly to the vault contract, and the vault shares are held by your wallet. StockYield has no smart contract for this strategy, no database of balances and never sees your keys." },
  { q: "Which asset and network do I need?", a: "USDG on Robinhood Chain (chain ID 4663), plus a small amount of ETH on the same network to pay transaction fees." },
  { q: "Why do I need ETH?", a: "Every transaction on Robinhood Chain pays a network fee in ETH. StockYield does not receive it. An estimate appears in Yield Check and your wallet shows the final fee before you sign." },
  { q: "Why are there two transactions?", a: "The first, Approve, lets the vault take exactly the USDG amount you entered. The second, Deposit, moves it into the vault. If your allowance is already enough, only Deposit is needed. StockYield does not ask for an unlimited allowance by default." },
  { q: "Can I withdraw at any time?", a: "Withdrawals follow the vault contract's rules and the liquidity available in the underlying lending markets, so StockYield cannot promise that your whole position can be withdrawn immediately. Every withdrawal is simulated before you sign, and you are told if it would fail." },
  { q: "Is the APY guaranteed?", a: "No. It is variable and can rise, fall or be zero. The rate shown is the net APY reported by Morpho (after vault fees, including rewards). Capital is at risk." },
  { q: "What fees apply?", a: "The vault can charge a management fee and a performance fee; current values are shown live in Strategy details. StockYield charges no fee. You also pay the network fee in ETH." },
  { q: "Do I need the SYELD token?", a: "No. The SYELD token is not needed to deposit, withdraw or earn in this strategy, and it does not change your yield." },
];
